name = "brevo-api"
main = "src/index.js"
compatibility_date = "2023-05-18"

# Usar workers.dev en lugar de un dominio personalizado
workers_dev = true

# Habilitar logs para depuración
[build.upload]
format = "service-worker"

# Add secret binding
[vars]
# This is just a placeholder, the actual value will come from your secret
BREVO_API_KEY = ""

[[secrets]]
name = "BREVO_API_KEY"