name = "brevo-api"
main = "src/index.js"
compatibility_date = "2023-09-04"

[vars]
# Variables públicas aquí (si las necesitas)

# Las variables secretas se configuran con el comando wrangler
# wrangler secret put BREVO_API_KEY